### ISSUE TITLE
[Feature request] Dynamic reconfiguration of relevant parameters

### ISSUE THREAD

**Issue by cailloumax** [RoverRobotics/openrover_v2support#4]
While tuning the robot, it appears that constantly restarting the *roverrobotics.service* at every parameter change is kind of impractical. It would be really great if some relevant parameters could be tuned via the *dynamic_reconfigure* package: for example, PID gain, robot total mass and traction factor for the odometry correction...

Would it be feasible ? 

Thanks in advance

**Comment by drhieu** [comment]
Is there a reason why you are using roverrobotics.service to tune the robot instead of using the roslaunch manually?
If you are using roslaunch manually you can change the config and roslaunch right away. It is safer to tune PID with this manual launch rather than waiting for a service to fully shutdown and restart.
You can always terminate manual Roslaunch if your PID is over tuned 

We also try to keep our stack package agnostic
